name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      tf_action:
        description: "Terraform Action"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply

jobs:
  terraform:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Terraform init
      run: terraform init
      working-directory: terraform

    - name: Terraform plan
      if: inputs.tf_action == 'plan'
      run: terraform plan
      working-directory: terraform
      
    - name: Terraform apply
      if: inputs.tf_action == 'apply'
      run: terraform apply -auto-approve
      working-directory: terraform

    - name: Terraform output
      if: inputs.tf_action == 'apply'
      run: terraform output
      working-directory: terraform